"""add learner profiles and concept state

Revision ID: 51ecff03db5c
Revises: 
Create Date: 2026-09-02 22:32:00.362692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51ecff03db5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learner_profiles',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('top_down', sa.Float(), nullable=False),
    sa.Column('example_first', sa.Float(), nullable=False),
    sa.Column('causal_reasoning', sa.Float(), nullable=False),
    sa.Column('visual_structure', sa.Float(), nullable=False),
    sa.Column('code_preference', sa.Float(), nullable=False),
    sa.Column('preferred_depth', sa.String(length=20), nullable=False),
    sa.Column('pacing', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_concept_states',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('concept_id', sa.String(length=128), nullable=False),
    sa.Column('mastery_estimate', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('last_evidence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('misconception_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_user_concept_confidence_range'),
    sa.CheckConstraint('evidence_count >= 0', name='ck_user_concept_evidence_count'),
    sa.CheckConstraint('mastery_estimate >= 0 AND mastery_estimate <= 1', name='ck_user_concept_mastery_range'),
    sa.PrimaryKeyConstraint('user_id', 'concept_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_concept_states')
    op.drop_table('learner_profiles')
    # ### end Alembic commands ###
